# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='origin',
            field=models.ForeignKey(default=38L, on_delete=django.db.models.deletion.CASCADE, to='ACMS.state'),
        ),
    ]
