# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0002_patient_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hmo',
            field=models.ForeignKey(default=2L, on_delete=django.db.models.deletion.CASCADE, to='ACMS.hmo', verbose_name='hmo_id'),
        ),
    ]
