# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0003_auto_20161022_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(default='NIL'),
        ),
    ]
