# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0004_auto_20161022_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='card_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='othernames',
            field=models.CharField(default='NIL', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='NIL', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surname',
            field=models.CharField(max_length=50),
        ),
    ]
